title: HFS - CCQC
email: emitchell@uga.edu
description: >
  Research group website for Henry F. Schaefer III, director of the 
  Center of Computational Quantum Chemistry part of the
  Department of Chemistry at the University of Georgia. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CCQC_UGA

permalink: pretty
#favicon: /path/to/favicon.png
#hide_share_buttons: true
theme_color: '#b02b21'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr


# Build settings
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - kramdown-parser-gfm

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
